### PR TITLE
Fixed selected clients not showing in filter

### PR DESCRIPTION
**Pull request by abinashpa**
## Notion card
https://www.notion.so/saeloun/Frontend-revenue-by-clients-report-Previously-selected-filter-values-are-not-displayed-on-openin-1ac6884b9c584e62b21b49093fdf8e8e

## Summary
- On the revenue reports page, the selected client filter is not showing on the filter tab.

## Preview
https://www.loom.com/share/38b7b40195a84d5db2edf2d957383cf0

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by apoorv1316 — COMMENTED** [review]
@abinashpa When we have multiple clients selected and if we remove one of them from filters all the client's filters are removed. Can you check and fix it? https://www.loom.com/share/8fd4fab37fe64b26842837d87e9e0277

**Comment by abinashpa** [comment]
> @abinashpa When we have multiple clients selected and if we remove one of them from filters all the client's filters are removed. Can you check and fix it?

This is not part of the ticket so it's better if I fix it on another PR.

**Comment by apoorv1316** [comment]
> > @abinashpa When we have multiple clients selected and if we remove one of them from filters all the client's filters are removed. Can you check and fix it?
> 
> This is not part of the ticket so it's better if I fix it on another PR.

@abinashpa I will create a ticket for it. Pick up if it's assigned to you.

**Review by JijoBose — APPROVED** [review]

**Comment by apoorv1316** [comment]
@abinashpa Check the failing test

**Comment by supriya3105** [comment]
@apoorv1316 Please test this PR today.

**Pull request closed without merging**
