### PR TITLE
Restricted team page access for Employee role. Updated team policy.

### PR DESCRIPTION
**Pull request by deepti-kakade**
Notion: https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=2cc38eb0f24d4e6c8752e1ec592d30de&pm=s

**Description:**
User with an Employee role, should not be able to view the Team page when they login into Miru. 

**What Fixed:**

For the employee role, we have already restricted team page access from navigation. But we were able to access it through the URL. To fix this issue we modified the Team policy(index action) for employee role.

Now when an employee accesses the team page from the URL it will throw an unauthorized error.

**Screenshot:**

Screenshot 2023-02-14 at 1 40 24 PM

### CODE REVIEW

**Comment by apoorv1316** [comment]
@deepti-kakade Please update the failing specs as per the new change.

**Comment by deepti-kakade** [comment]
@apoorv1316 Fixed test cases you can re-review this PR.

**Comment by supriya3105** [comment]
@shalapatil please review today

**Review by vipulnsward — APPROVED** [review]
@deepti-kakade please merge when CI is green

**Pull request merged**
