### PR TITLE
Redevelop Organization settings page on React

### PR DESCRIPTION
**Pull request by sanjibroy360**
## Notion card
[https://www.notion.so/saeloun/Redevelop-Organization-settings-page-on-React-c8be7c2da40b495aa99f909a0dc93329](https://www.notion.so/saeloun/Redevelop-Organization-settings-page-on-React-c8be7c2da40b495aa99f909a0dc93329)

## Figma
[https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?node-id=6785%3A69202&t=XIl2Dw7VK8ro6jj3-0](https://www.figma.com/file/4gdPDRPqGqQqPYsO3Qj8CG/Miru-App?node-id=6785%3A69202&t=XIl2Dw7VK8ro6jj3-0)
## Summary
Redeveloped the Organization setup page on React

## Preview
[https://www.loom.com/share/34af6d68cacf4517b758d6a19419f74e](https://www.loom.com/share/34af6d68cacf4517b758d6a19419f74e)

## Type of change
Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by onkar-saeloun — COMMENTED** [review]
Please go through the comments

**Review by onkar-saeloun — APPROVED** [review]
LGTM

**Comment by supriya3105** [comment]
@apoorv1316 Please test and @AkashKale Please do a UI review.

**Comment by supriya3105** [comment]
@sanjibroy360 Please check the tests that are failing on this PR.

**Comment by supriya3105** [comment]
@apoorv1316 Please test this today.

**Comment by apoorv1316** [comment]
@sanjibroy360 Why are Address line 2, state, city, and zip code fields not present? It is in the designs and also in the notion description.

**Comment by sanjibroy360** [comment]
> @sanjibroy360 Why are Address line 2, state, city, and zip code fields not present? It is in the designs and also in the notion description.

As @supriya3105 suggested for now we are showing all the fields that we used to show earlier so that it won't require any backend API changes.

**Comment by apoorv1316** [comment]
@sanjibroy360 Business phone validations are not correct. It is accepting A-Z letters also. Also the default date format should be MM-DD-YYYY.

**Comment by AkashKale** [comment]
Where can I review this. Is it deployed somewhere? @supriya3105 @sanjibroy360

**Comment by supriya3105** [comment]
> > @sanjibroy360 Why are Address line 2, state, city, and zip code fields not present? It is in the designs and also in the notion description.
> 
> As @supriya3105 suggested for now we are showing all the fields that we used to show earlier so that it won't require any backend API changes.



> > @sanjibroy360 Why are Address line 2, state, city, and zip code fields not present? It is in the designs and also in the notion description.
> 
> As @supriya3105 suggested for now we are showing all the fields that we used to show earlier so that it won't require any backend API changes.



> > @sanjibroy360 Why are Address line 2, state, city, and zip code fields not present? It is in the designs and also in the notion description.
> 
> As @supriya3105 suggested for now we are showing all the fields that we used to show earlier so that it won't require any backend API changes.

@sanjibroy360 @apoorv1316 Notion ticket has been updated and address field changes have been added to out of scope for this notion ticket.

**Review by apoorv1316 — APPROVED** [review]

**Review by AkashKale — APPROVED** [review]
All my feedback comments are implemented.

**Pull request merged**
