### PR TITLE
Bug in the line items list when editing a line item

### PR DESCRIPTION
**Pull request by rajat-tomar**
## Summary
This fixes bug on create new invoice page when you editing an invoice entry and press create new item button. Date used to persist over the modal which is now resolved.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by rajat-tomar** [comment]
@apoorv1316 why is this check failing?

**Comment by rajat-tomar** [comment]
@akhilgkrishnan is there some issue with this PR?

**Review by akhilgkrishnan — APPROVED** [review]
LGTM. Thanks @rajat-tomar for working on this

**Comment by akhilgkrishnan** [comment]
@apoorv1316 Please test this ticket

**Review by apoorv1316 — APPROVED** [review]

**Comment by apoorv1316** [comment]
@rajat-tomar Thanks for working on it!

**Pull request merged**
