### PR TITLE
Custom icons are added to miruIcons

### PR DESCRIPTION
**Pull request by abinashpa**
## Notion card
https://www.notion.so/saeloun/Move-SVG-s-from-assets-to-miru-icons-All-icons-should-be-moved-to-Miru-icons-3b1be09428e8447690ea62ab3fd66e2b

## Summary
- SVG icons located in `app/assets/images` added to miruIcons
- Fixed the Team icon in the nav bar

## Preview
Screenshot 2023-01-02 at 11 20 05 PM

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking and retains the same functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by prasanthchaduvula — APPROVED** [review]

**Comment by apoorv1316** [comment]
@abinashpa No loom video or image? It is a frontend change please add something to the preview.

**Comment by apoorv1316** [comment]
@abinashpa App is breaking. Please check
Screenshot 2023-01-02 at 12 58 41 PM

**Comment by abinashpa** [comment]
@apoorv1316 How? Working fine for me.

**Comment by apoorv1316** [comment]
> @apoorv1316 How? Working fine for me.

even if I comment this line from code I get an error from some other icon. Something is wrong

**Comment by abinashpa** [comment]
> > @apoorv1316 How? Working fine for me.
> 
> even if I comment this line from code I get an error from some other icon. Something is wrong

Fixed 👍

**Comment by supriya3105** [comment]
@apoorv1316 Lets test it today and share your test results.

**Comment by apoorv1316** [comment]
@abinashpa The pencil icon is so small on add entry card. cc @supriya3105 
Screenshot 2023-01-03 at 1 47 51 PM

**Comment by abinashpa** [comment]
> @abinashpa The pencil icon is so small on add entry card. cc @supriya3105 Screenshot 2023-01-03 at 1 47 51 PM

Fixed.

**Review by apoorv1316 — APPROVED** [review]

**Pull request merged**
