### PR TITLE
Update StyledComponents typography from lowerCamelCase to CamelCase

### LINKED ISSUE #686: Update tsconfig.json & alias.js with StyledComponents path.
### Is your proposal related to a problem?

- Currently to import `styledComponents` in other components we are using relative path imports which is annoying for common reusable styled components.
for example we are doing `import { Badge } from "../../../styledComponents"` in the other components by passing relative path to the styledComponents folder.

### Describe the solution you'd like
`import { Badge } from "StyledComponents"`

Please change the `styledComponents` folder name to `StyledComponents` . Update `tsconfig.js` paths with StyledComponents 
similar to:
```
"paths": {
      // previous code
      "StyledComponents": ["./app/javascript/src/StyledComponents"],
    }
    
```
  Update `alias.js` with `StyledComponents` path similar to 
  ```
module.exports = {
  resolve: {
    alias: {
      // previous code
      StyledComponents: "src/StyledComponents",
    }
  }
};

```

Update the StyledComponents import path across the app like `import { Badge } from "StyledComponents"` instead of relative path.

### PR DESCRIPTION
**Pull request by aaj013**
## Summary
Closes #686

## Preview

https://user-images.githubusercontent.com/5847582/193656588-46437c96-d020-4366-ae22-88a6f229c6d0.mp4

## Type of change
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
No errors in running `foreman start -f Procfile.dev` and `bundle exec rspec`

### Checklist:
- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by prasanthchaduvula** [comment]
@aaj013 please post the app demo by running the app in your local. Code changes LGTM.

**Comment by aaj013** [comment]
> @aaj013 please post the app demo by running the app in your local. Code changes LGTM.

You mean screen video of whether app's working from this branch? If yes, I can do that. Else I didn't understand/

**Comment by prasanthchaduvula** [comment]
@aaj013 Yes. Please post the screen recording of this PR app by running in your local.

**Comment by aaj013** [comment]
> @aaj013 Yes. Please post the screen recording of this PR app by running in your local.

Will do it now

**Review by prasanthchaduvula — APPROVED** [review]
LGTM

**Review by akhilgkrishnan — APPROVED** [review]
Thanks @aaj013 for working on this 👍

**Pull request merged**
