### PR TITLE
View holidays calendar

### PR DESCRIPTION
**Pull request by prasanthchaduvula**
#### What
- View national holidays and optional holidays on the calendar
- Fixed the date picker edit bug on the edit holidays page
- Fixed the date format on the holiday module to align with organization level date format

#### Demo
https://www.youtube.com/watch?v=uUp0Bu9VBv8

### CODE REVIEW

**Comment by apoorv1316** [comment]
@prasanthchaduvula Please work on the changes discussed in the call.

**Comment by apoorv1316** [comment]
@prasanthchaduvula Please fix the bugs related to date format, calendar view, and year list as we discussed in the call.

**Review by apoorv1316 — APPROVED** [review]
@prasanthchaduvula Please remove the cursor pointer and background color on hover on the calendar
Screenshot 2023-10-20 at 12 05 43 PM

**Comment by prasanthchaduvula** [comment]
@apoorv1316 If we remove the background colour and cursor pointer on hover then user wont receive the feedback

**Comment by apoorv1316** [comment]
@prasanthchaduvula Nothing happens when we click on the calendar date. It's there just for viewing the holidays.
Are we going to add any functionality to it in the future?

**Pull request merged**
