### PR TITLE
Optimize and moved project_list method to service

### PR DESCRIPTION
**Pull request by abinashpa**
## Summary
- The `project_list` method in the Company model uses N+1 times transaction to fetch and manipulate the data for /projects page. The method now uses a single query to fetch the project details of a company. The `project_list` method is now moved to its respective services called `ProjectListService `. 
- Rspec test removed from methods that are moved to its service.

## Preview
Screenshot 2023-01-02 at 2 10 24 PM

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking and retains the same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by supriya3105** [comment]
@abinashpa Please update the branch

**Comment by abinashpa** [comment]
@swaathi I have added memoization for `ProjectListService#project_list_query`

**Comment by abinashpa** [comment]
@swaathi
- Renamed both method and the variable name `project_list_query`.
- I did a self-review of my code but I get very few rails tasks so it's hard to practice all of them, please be explicit in my review.
- I did change the summary, you can check the history.
- All Rspec tests are passing, but CI is failing because of an OpenSSL issue over which I don't have any control.

**Comment by abinashpa** [comment]
CI is passing now.

**Pull request merged**
