### PR TITLE
Empty state invoice page

### PR DESCRIPTION
**Pull request by Shruti-Apte**
## Notion card
https://www.notion.so/saeloun/Implement-Empty-state-design-on-Invoice-page-81d3e086cd8a47f9894fcf0cadd6d8d4
## Summary

- Empty state added for invoice list page.
- Hover effect fixed for filter icon.
## Preview

https://www.loom.com/share/12e17d80229e4353bc2a68857cd23fbc
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [x] This change requires a documentation update

## How Has This Been Tested?
- Checked on responsive screens 
- Navigation working

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by prasanthchaduvula — CHANGES_REQUESTED** [review]

**Comment by apoorv1316** [comment]
@Shruti-Apte Let me know what you and Sonam decided for the empty state in case of 0 in the draft, overdue and outstanding

**Comment by Shruti-Apte** [comment]
> @Shruti-Apte Let me know what you and Sonam decided for the empty state in case of 0 in the draft, overdue and outstanding

Connected with @supriya3105 and updated the PR according to discussion!

**Comment by apoorv1316** [comment]
@Shruti-Apte I have to refresh the invoices pages to see the latest created invoice. Can you please fix it. https://www.loom.com/share/3becb2584f9d469eac5b155f5b3c1d30

**Comment by apoorv1316** [comment]
> @Shruti-Apte I have to refresh the invoices pages to see the latest created invoice. Can you please fix it. https://www.loom.com/share/3becb2584f9d469eac5b155f5b3c1d30

It needs investigation from the backend. Approving this PR

**Review by apoorv1316 — APPROVED** [review]

**Review by prasanthchaduvula — APPROVED** [review]

**Pull request merged**
