### PR TITLE
client page alignment fixed

### PR DESCRIPTION
**Pull request by Ankita012**
## Notion card
https://www.notion.so/UI-changes-in-client-page-48fb0572542b48f0a71cd2d752b74955

## Summary
Client page font and alignment fixed

## Preview
Screenshot 2023-01-25 at 2 36 04 PM

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains the same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
Checking the font size and client of all the text by inspecting on the browser.

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@Ankita012 Please update the font size of hours-logged to 20px.

**Comment by apoorv1316** [comment]
@Ankita012 Ignore the font size comment but fix the alignment of the "Outstanding" section. 
Screenshot 2023-01-27 at 12 12 56 PM

**Comment by Ankita012** [comment]
> @Ankita012 Please update the font size of hours-logged to 20px.
It's already there

**Comment by Ankita012** [comment]
> @Ankita012 Ignore the font size comment but fix the alignment of the "Outstanding" section. Screenshot 2023-01-27 at 12 12 56 PM

Fixed

**Review by apoorv1316 — APPROVED** [review]

**Pull request merged**
