### PR TITLE
More options mobile view design

### PR DESCRIPTION
**Pull request by Shruti-Apte**
## Notion card
https://www.notion.so/saeloun/More-Options-from-navigation-menu-77232415c44a45c8836e68c23e959774
## Summary

- More option navigation design for mobile view.
- Refactoring
## Preview

Admin Role
Screenshot 2023-01-18 at 12 27 06 PM
Employee role: 
Screenshot 2023-01-18 at 12 27 57 PM

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?
- Checked for mobile view and desktop view 

- Checked design on each responsive view. 
### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by supriya3105** [comment]
@Shruti-Apte The spacing between the various modules does not seem to be as per the designs. 
The help option is missing. Also, have you implemented it for employee role as well ? Please check notion for the designs. 

https://www.notion.so/saeloun/More-Options-from-navigation-menu-77232415c44a45c8836e68c23e959774

**Comment by supriya3105** [comment]
@Shruti-Apte Have you checked this ?

**Comment by Shruti-Apte** [comment]
> @Shruti-Apte The spacing between the various modules does not seem to be as per the designs. The help option is missing. Also, have you implemented it for employee role as well ? Please check notion for the designs.
> 
> https://www.notion.so/saeloun/More-Options-from-navigation-menu-77232415c44a45c8836e68c23e959774

Do we have help page? Implemented for employee as well!

**Comment by supriya3105** [comment]
@Shruti-Apte Please update the PR with screenshot for employee role as well.

**Review by prasanthchaduvula — APPROVED** [review]

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@Shruti-Apte We are not showing a profile picture of a user on navigation even if it is attached. Also after exiting from mobile view we get an error message. Please fix it. https://www.loom.com/share/7d172371affc4e0d80bff822a6af388d

**Review by apoorv1316 — APPROVED** [review]

**Pull request merged**
