### PR TITLE
replaced svg code and image of twitter

### PR DESCRIPTION
**Pull request by chaursiyasanjeet**
issue #1499 
change the SVG code of Twitter with new logo SVG code 
Twitter PNG file also replaced

Here are the screenshots of the final view 
 
image

### CODE REVIEW

**Comment by akhilgkrishnan** [comment]
@chaursiyasanjeet Please check https://github.com/saeloun/miru-web/issues/1499#issuecomment-1744468643

**Comment by supriya3105** [comment]
@apoorv1316 Please check this PR and provide feedback if any.

**Comment by chaursiyasanjeet** [comment]
There is an old Twitter logo in this repo so, I replaced that with the new X logo. 
you can check in file changes I just replaced the old SVG graphic code of Twitter and one PNG   with a new X logo, so it will enhance.

**Comment by chaursiyasanjeet** [comment]
You're welcome

**Pull request merged**
