### PR TITLE
Fixed the issue in assigning role to team member

### PR DESCRIPTION
**Pull request by gowsik-ragunath**
## Slack message link

https://saelounus.slack.com/archives/C03GHMCAMST/p1655970158725439

## Summary

Fixed the issue in update team action when the role is not passed in params.

To reproduce this issue,

- In Edit team member form uncheck any selected roles (can be done by updating the HTML in inspect)
- Submit the form and it will show an error flash message.

## Preview

Screenshot 2022-06-23 at 5 00 03 PM

Screenshot 2022-06-23 at 5 00 11 PM

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [X] I have manually tested all workflows
- [X] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by abinashpa — COMMENTED** [review]
LGTM

**Comment by supriya3105** [comment]
@apoorv1316 Please check the sign up and add team members functionality for this PR.

**Comment by supriya3105** [comment]
@apoorv1316 Please test the add team member functionality for this PR.

**Comment by supriya3105** [comment]
@rohitjoshixyz Please review this PR.

**Review by rohitjoshixyz — APPROVED** [review]
LGTM

**Pull request merged**
