### PR TITLE
JS import order arranged

### PR DESCRIPTION
**Pull request by akhilgkrishnan**
## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by akhilgkrishnan** [comment]
@apoorv1316 can you do a smoke test on this branch on your local?

**Comment by apoorv1316** [comment]
@akhilgkrishnan I am not able to make payment on this branch. Stripe is connected. Please see the attached loom
http://localhost:3000/invoices/3b25964a16d556e53f8684018794da9c/view

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan I am not able to make payment on this branch. Stripe is connected. Please see the attached loom http://localhost:3000/invoices/3b25964a16d556e53f8684018794da9c/view

@apoorv1316 can you share the loom video

**Comment by apoorv1316** [comment]
> > @akhilgkrishnan I am not able to make payment on this branch. Stripe is connected. Please see the attached loom http://localhost:3000/invoices/3b25964a16d556e53f8684018794da9c/view
> 
> @apoorv1316 can you share the loom video

@akhilgkrishnan Sorry, here is the loom https://www.loom.com/share/824ff744a5df4567b3389e4cc2ac53c5

**Review by apoorv1316 — APPROVED** [review]

**Pull request merged**
