### PR TITLE
Fixed reset and filter counter issue on Revenue filter page

### PR DESCRIPTION
**Pull request by Ankita012**
Summary: 
Fixed reset and filter counter issue on the Revenue filter page
Preview: 
https://www.loom.com/share/7a58f8842d3e4ecdbb71818d2f69c792

### CODE REVIEW

**Review by prasanthchaduvula — CHANGES_REQUESTED** [review]

**Comment by prasanthchaduvula** [comment]
@apoorv1316 Please test this PR before mergin it

**Comment by onkar-saeloun** [comment]
@Ankita012 Apoorv has raised issues on the UI of filter panel let me know how much work is done in the current PR.
https://www.notion.so/saeloun/Update-the-UI-for-filter-panel-on-revenue-report-094a8bec41a24a079694e37fd4851dc6?pvs=4

**Review by prasanthchaduvula — APPROVED** [review]

**Comment by prasanthchaduvula** [comment]
@Ankita012 Please update

> @Ankita012 Apoorv has raised issues on the UI of filter panel let me know how much work is done in the current PR. https://www.notion.so/saeloun/Update-the-UI-for-filter-panel-on-revenue-report-094a8bec41a24a079694e37fd4851dc6?pvs=4

**Comment by Ankita012** [comment]
> @Ankita012 Apoorv has raised issues on the UI of filter panel let me know how much work is done in the current PR. https://www.notion.so/saeloun/Update-the-UI-for-filter-panel-on-revenue-report-094a8bec41a24a079694e37fd4851dc6?pvs=4

on Press ESC key panel gets closed fixed.
on selection of clients All clients option removed from the main screen got fixed.
on clearall, all filters were removed. Fixed.
All filter counter things are working- Fixed

**Review by onkar-saeloun — APPROVED** [review]

**Pull request merged**
