### PR TITLE
Update the cypress specs

### PR DESCRIPTION
**Pull request by apoorv1316**
## Summary
The cypress tests that are written need to be updated because of the changes done in the app.

Screenshot 2022-07-07 at 10 23 37 AM

### CODE REVIEW

**Review by akhilgkrishnan — COMMENTED** [review]
@apoorv1316 Can you add the cypress test in our CI. I think we were removed that previosly

**Comment by apoorv1316** [comment]
@akhilgkrishnan Yes will do that!

**Comment by apoorv1316** [comment]
@mohinid Updating old specs as per the changes made in the app.

**Comment by apoorv1316** [comment]
@mohinid Please review it.

**Review by mohinid — APPROVED** [review]
LKTM! :)
Screenshot 2022-07-07 at 12 56 30 PM

**Pull request merged**
