### PR TITLE
Fix: Data not loading sometimes when paginating on time entry reports page

### PR DESCRIPTION
**Pull request by mayankagnihotri7**
## Notion Card
[Notion Card](https://www.notion.so/saeloun/Bugs-after-deployment-7752310dde324ef897c44dd7eee12ebb)

## Description
- This is a fix for data not loading sometimes when paginating on the time entry reports page.
- The reason the issue was occurring was that IDs for that page's data were being stored first and paginated and then used for searching the time entries. When no entries were found, they were returning an empty array; since they were already paginated, they were returned to an empty page.

## Preview
- Before

https://github.com/saeloun/miru-web/assets/57438322/e9d018b7-0232-471e-ba9a-dc04ab103865

- After

https://github.com/saeloun/miru-web/assets/57438322/b3b8f4c5-4760-46f6-9ed1-b51d4538891e

### CODE REVIEW

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Please update the branch with develop, create an env `SEED_DATA_FROM_CSV=true` and run timesheet_data.rake file, and then test the time entry reports.

**Comment by apoorv1316** [comment]
@mayankagnihotri7 @supriya3105 Please watch these loom videos 
https://www.loom.com/share/e8275be98dc04af1ab65c42d9df429db
https://www.loom.com/share/1acadee876234670a57dfe5cbd40ac20

- Page is becoming unresponsive because it's fetching all entries and showing them on one page if no. of clients are less and grouped by none.
- Throwing toaster error when clicking on three dots on pagination.
- Pagination not working correctly on using group by project

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Next button is not visible even though we have 2 pages on the invoices page. Please check this too.
Screenshot 2023-05-29 at 11 37 32 AM

**Comment by apoorv1316** [comment]
@mayankagnihotri7 What's remaining here?

**Comment by mayankagnihotri7** [comment]
Fixing test cases and also another bug cropped up

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Did you fixed the bug in Group by Project?

**Comment by mayankagnihotri7** [comment]
Yes

**Comment by supriya3105** [comment]
@apoorv1316 Please test this on priority.

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Please work on adding capybara specs for the time entry reports. Add detailed specs for this feature including the filters, group by and pagination.

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@mayankagnihotri7 Group by project and team member is still not fixed. It has bugs in showing data and moving to different pages.
https://www.loom.com/share/da78316dfba642b7bd49c02e9db64b3e
 I think there will be bugs in the group by clients too. Create 7-8 clients in seed file with each having at least 50 entries and then test it.

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Please see the loom video and fix the bugs mentioned in it.
https://www.loom.com/share/164fd29085f34bd5a3c34d9f171ecbba

**Comment by gowsik-ragunath** [comment]
@Apoorv I have fixed the pagination issue.

Status filter does works. The reason why non billable and billed filter didnt worked in your case is I think the records created using the csv(seed data) only has `unbillable` status.

Please set status of some records to non billable and billed this will make the filter work.

**Comment by apoorv1316** [comment]
@gowsik-ragunath 
Few concerns
- There should not be multiple pagination dots it will create a bug (see 2nd image ). 2 can be the max number one for moving to the prev pages and another one for the following pages.
- No result when group by none is applied
Screenshot 2023-06-22 at 12 13 42 PM
Screenshot 2023-06-22 at 12 14 20 PM
Screenshot 2023-06-22 at 12 28 34 PM
Screenshot 2023-06-22 at 12 29 48 PM

**Comment by gowsik-ragunath** [comment]
@apoorv1316 I have fixed those issue in [this commit](https://github.com/saeloun/miru-web/pull/1334/commits/2ae87d0797e33d3865fbd701c3ec07f9cf5794c4) but some how these changes are reverted when the develop branch is merged yesterday. I will add them again.

**Comment by gowsik-ragunath** [comment]
@apoorv1316 I have fixed the group with none, pagination and test issue

Demo: https://youtu.be/_7Qv8X_j6ZE

**Review by apoorv1316 — APPROVED** [review]

**Pull request merged**
