### PR TITLE
Fixed entries & calendar mismatch bug on time tracking when changing months

### PR DESCRIPTION
**Pull request by prasanthchaduvula**
## Notion card
https://www.notion.so/6afc9500b2cc42af86be55f37894fb09?v=185bd45b9dc24dfcad9c57c07d32a7c0&p=8f29bf066dad440480f441d9b2022d41&pm=s

## Summary

- This PR fixes the bug on the time tracking when changing months.
- Before, we showed the monthly calendar along with entries based on first-day value. eg: In 2023, Feb 1st & March 1st are on Wednesday. In the codebase, the entries & calendar are refreshed based on `useEffect` depending on the first day. We never noticed this bug as we have never seen the first day falls on the same day for consecutive months. But this year 2023 it happened for Feb & March months as the first day of both months falls on Wednesday.

## Preview

**Before**

https://user-images.githubusercontent.com/52771571/211954905-e4fe50fa-07c6-4bfd-8516-a0c10142666d.mov

**After**

https://user-images.githubusercontent.com/52771571/211956195-755b74fc-69de-4915-9a32-f1817f2c6c71.mov

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by supriya3105** [comment]
@apoorv1316 Please test on priority

**Review by apoorv1316 — APPROVED** [review]
@prasanthchaduvula Thanks for fixing it at 🚀 speed. https://www.loom.com/share/e23f16f394bb4a1c94848a10cc24fec0 cc @supriya3105

**Comment by supriya3105** [comment]
@prasanthchaduvula update the branch. I tried from my end by the build wasn't running.

**Comment by apoorv1316** [comment]
@supriya3105 There are other CI and CD builds already in the queue that's why it is not running.

**Pull request merged**
