### PR TITLE
Fixed address field on organisation edit page

### PR DESCRIPTION
**Pull request by Shruti-Apte**
closes : #1678 
loom: https://www.loom.com/share/3c6a0d26935142d891d352c777213d72?sid=c2ac9507-ca43-4efe-a6e6-0466ce4e3c47

### CODE REVIEW

**Comment by apoorv1316** [comment]
Please add loom with edge cases and get it confirmed from Sonam

**Comment by nisusam** [comment]
Would you like to have this in address line 2 as well @apoorv1316, @sonamvg, @supriya3105?

**Comment by supriya3105** [comment]
@Shruti-Apte @nisusam Yes. The same changes should be applicable on the address line 2 field as well. Also @Shruti-Apte Can you share the validations that have been added to all the address related fields ?

**Comment by Shruti-Apte** [comment]
@supriya3105 Validations for address fields:

Address line 1:
- Address Line 1 cannot be blank
- Maximum 50 characters are allowed

Address line 2:
- Maximum 50 characters are allowed

**Review by supriya3105 — APPROVED** [review]

**Review by nisusam — APPROVED** [review]

**Pull request merged**
