### PR TITLE
Auto save time tracking entries into local storage

### PR DESCRIPTION
**Pull request by qianzhong516**
## Problem
Reference https://github.com/saeloun/miru-web/issues/1495. 

## Scenarios accounted for in this PR
1. Save info into local storage simultaneously when user updates the entry form
2. Save form info based on the selected date
3. Clear time tracking local storage on save, edit and cancel

## Solution
Saving the time tracking info into local storage in the following format:
```ts
{ [key: selectedDate]: { editEntryId, client, project, billable, duration, note }[] }
```

## Things to consider
`billable` is synced automatically based on the project settings. If user changes a preset billable project to non-billable in one entry, even though the correct info is saved locally, they still see the entry billable in the next visit.

## Demo
https://drive.google.com/file/d/1oWkiLfcT2TmkjtumsfVxHNec-edjXOfi/view?usp=sharing

### CODE REVIEW

**Comment by prasanthchaduvula** [comment]
@qianzhong516 Currently, in this PR, what you implemented is saving new timesheet entries & edit entries on multiple dates with multiple new entries on dates with flexibility.  On the other hand, it adds many entries to local storage which is unnecessary for the user. We are running multiple `useEffect` for the same. 

The requirement is we have to save only one entry to local storage whatever they are adding as a new timesheet entry and when they click on a new entry on any date it should select the client, project and description they have added.

This feature is not required for edit timesheet entries. This feature is required for the new timesheet entries
Example:
On a new timesheet entry, If the user added details on the selected date and moved away from the page.
When the user clicks on a new timesheet entry on any date it should populate with the previous data whatever is added but the date should not be preloaded and it should be always the date selected from the view. 

**Feature is required for only new timesheet entries**

**Comment by qianzhong516** [comment]
Hey @apoorv1316, could you confirm what @prasanthchaduvula said above? That requirement is different from what I referred to the [video description](https://www.loom.com/share/bb2907fec1264066ba38299aa46c9a39) linked in the [PR](https://github.com/saeloun/miru-web/issues/1495) tho. Also cc @supriya3105

**Comment by apoorv1316** [comment]
@qianzhong516 Hi, Sorry for the confusion. I discussed it with Prasanth and we decided to go with new timesheet entries for now. So that we can test it out properly with the current user base. Please make the required changes. Thanks

**Comment by qianzhong516** [comment]
Sorry @apoorv1316 , I won't be able to work on this anymore. Please assign someone else, thanks.

**Pull request closed without merging**
