### PR TITLE
common component used for client logo

### PR DESCRIPTION
**Pull request by Shruti-Apte**
## Notion card
- https://www.notion.so/saeloun/Use-Avatar-common-component-for-displaying-client-images-on-the-client-list-page-eeaf5ac8410049c8af80b41cff89491a
## Summary

- Common avatar component used for client page.
- Accounts aging header spacing fixed for mobile view.

## Preview

Screenshot 2023-01-24 at 12 15 13 PM

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by apoorv1316** [comment]
@Shruti-Apte Please see the loom video https://www.loom.com/share/9450976bde704f8694d8443164974a95 cc @supriya3105

**Comment by apoorv1316** [comment]
@Shruti-Apte This is some weird behavior on deleting logo https://www.loom.com/share/926d4a2f7cab48b0a2feaf4a579151ff

**Comment by supriya3105** [comment]
@apoorv1316 Please test this again and approve if everything is working fine.

**Comment by apoorv1316** [comment]
@Shruti-Apte On the new client modal image is not showing up after attaching. https://www.loom.com/share/264e34c8af5644b0883028a9dbc729bb

**Review by apoorv1316 — APPROVED** [review]

**Pull request merged**
