### PR TITLE
Fix: Inaccurate quantity while generating a invoice

### PR DESCRIPTION
**Pull request by mayankagnihotri7**
## Notion card
[Notion Card](https://www.notion.so/saeloun/Inaccurate-qty-while-generating-an-invoice-35dc45c52d694f7e92d9fbe442c7f696)

## Summary

Quantity was not being shown correctly on the generate invoice page.

## Preview

Video - https://www.awesomescreenshot.com/video/10960352

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@mayankagnihotri7 The issue still persists. The time entry is 8:37 but in the invoice, it's showing as 8:62.  Let me know if you need help in understanding the issue better.
Screenshot 2022-09-09 at 9 46 48 AM
Screenshot 2022-09-09 at 9 47 17 AM

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Please ignore the above comment. I pulled your branch but forgot to check out of develop. Sorry, my bad.

**Review by apoorv1316 — COMMENTED** [review]
@mayankagnihotri7 LGTM.  @supriya3105 Checked it with the whole July month entries of a user and with creating new entries too. It works fine. Can you or Mohini still check it with me just to be absolutely sure?

**Comment by mayankagnihotri7** [comment]
@apoorv1316 Please approve the changes and merge it, if it works fine.

**Review by JijoBose — APPROVED** [review]

**Review by apoorv1316 — APPROVED** [review]

**Pull request merged**
