### PR TITLE
Remove default scope 'kept' from projects & clients model

### PR DESCRIPTION
**Pull request by mohinid**
## Notion card
https://www.notion.so/saeloun/Remove-default-scope-kept-from-project-rb-996d2f3884954f35beff5646a6ef043d

## Summary
The default scope was set to only return results that are kept (i. e. not discarded). Now by removing we can get the discarded projects as well. This resolves a production bug.

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?
By running rspecs & rails console
Tested scenarios on local - https://github.com/saeloun/miru-web/pull/739#issuecomment-1306829176

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have added automated tests for my code

### CODE REVIEW

**Comment by mohinid** [comment]
> @mohinid what about the client.rb

done. Testing it now.

**Comment by mohinid** [comment]
@akhilgkrishnan  can you pls review this pr?

**Review by akhilgkrishnan — COMMENTED** [review]
@mohinid can you check the other places which calling clients and project models, would they really need the kept?

**Comment by mohinid** [comment]
> @mohinid can you check the other places which calling clients and project models, would they really need the kept?

Hey no. I checked. Could find only these 2 places.

**Review by apoorv1316 — APPROVED** [review]

**Comment by mohinid** [comment]
1. Deleted client/project should not affect any flow. 
2. The deleted client/project should not be listed anywhere except client/project page. @supriya3105 to answer.
3. Check if we need deleted client/project for any calculations. So there add a condition- with discarded. 
@mohinid

**Comment by supriya3105** [comment]
> * Deleted client/project should not affect any flow.
> * The deleted client/project should not be listed anywhere except client/project page. @supriya3105 to answer.
> * Check if we need deleted client/project for any calculations. So there add a condition- with discarded.
>   @mohinid

On the clients/projects page, the data for the not deleted entries should be displayed. The data of discarded clients should not be displayed. The. clients data should be retained on invoices, payments and all the reports. 

If we delete a project, then the data for that project should not displayed on the clients.

**Comment by mohinid** [comment]
Tests-
https://saeloun.slack.com/archives/D026R6WP0NS/p1667895963624009

Expected behavior -
1. On the clients/projects page, the data for the deleted entries should not be displayed. (only should be visible in archive projects/clients- new feature)
2. The deleted client/project should not be listed anywhere except on the client/project page. **Passing** - Results- Not displayed on TS, Clients(), Projects,
3. The data of discarded clients should not be displayed. - Ok
4. The projects'/clients' data should be retained on invoices, payments, and all reports. - **Failing** (Need to fix as per requirements) - Deleted client also deleted from invoice. (that was already sent), deleted clients deleted from from reports,  Deleted project data displayed on TS reports (correct), deleted client deleted from revenue report as well. (

**Comment by mohinid** [comment]
@apoorv1316 please test the above-mentioned scenario- https://github.com/saeloun/miru-web/pull/739#issuecomment-1306829176 and confirm the results. 

@supriya3105  Meanwhile I am fixing the **Bug->** 
Deleted clients/projects are displayed in TS entry dropdown for new entries. 
Expected - >Deleted client/projects- Should not be present in the list.

**Note:-** Supriya to open new tickets
-  For pending Draft Invoice /TS entries for a client which is to be deleted, user should be given a prompt to complete pending actions before performing delete actions.
- Bug in bookkeeper role. as mentioned above.

**Comment by apoorv1316** [comment]
@mohinid 
- Deleted project/client is not on the project/client page list. 
- TS for deleted projects/clients is visible. 
- Invoice of deleted client/project and the data is displayed in all the reports.
- Deleted project/client not showing while creating new ts entry.

**Review by akhilgkrishnan — APPROVED** [review]
LGTM

**Pull request merged**
