### PR TITLE
Edit/delete existing line items

### PR DESCRIPTION
**Pull request by gowsik-ragunath**
## Summary

- Fixed the issue in editing and deleting existing line items.
- Existing line items can be added without pressing the `Enter` key.

## Preview

https://www.loom.com/share/fb6f2e070f32471b8f91be46e6653d34

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [X] I have manually tested all workflows
- [X] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by supriya3105** [comment]
@apoorv1316 Please test the complete invoice functionality for this PR.

**Comment by apoorv1316** [comment]
@gowsik-ragunath After editing a line item it remains in the editing state. Can we do something about it? Also on the edit invoice, there seems to be a CSS issue after editing the line item. Please check the video and let me know if you need more clarity on it. https://www.loom.com/share/e15ff2f89374470bb32bdee8f37090ab

**Comment by gowsik-ragunath** [comment]
@apoorv1316 I've fixed the issue in toggling between line item edit and view.

Demo: https://www.loom.com/share/f74f31f8a4f849fdbb5a4d93fb3ab284

**Review by apoorv1316 — APPROVED** [review]

**Review by sudeeptarlekar — APPROVED** [review]
overall looks good

**Pull request merged**
