### PR TITLE
New address change new pr

### PR DESCRIPTION
**Pull request by onkar-saeloun**
This PR is copy of https://github.com/saeloun/miru-web/pull/1116 all the changes are same

### CODE REVIEW

**Comment by apoorv1316** [comment]
@onkar-saeloun We are getting undefined for all address fields on client's view of invoice. Can you please check it?
Screenshot 2023-04-13 at 10 05 33 AM

**Comment by onkar-saeloun** [comment]
> @onkar-saeloun We are getting undefined for all address fields on client's view of invoice. Can you please check it? Screenshot 2023-04-13 at 10 05 33 AM

The issue is from backend @deepti-kakade can you please have a look into the issue

**Comment by prasanthchaduvula** [comment]
@apoorv1316 PLease test this PR once. I fixed the address on client invoice view

**Comment by apoorv1316** [comment]
@prasanthchaduvula @onkar-saeloun Getting this error after clicking on the view invoice button.
Screenshot 2023-04-17 at 10 22 45 AM
Screenshot 2023-04-17 at 10 22 50 AM

**Review by prasanthchaduvula — APPROVED** [review]

**Pull request merged**
