### PR TITLE
Fixed time entry report UI bug

### PR DESCRIPTION
**Pull request by gowsik-ragunath**
## Notion card

https://www.notion.so/saeloun/Bugs-in-Time-Entry-Report-116e6536ff87433ca8f7c0fe0852a54d

## Summary

- Added scroll bar to report filter to access `accept` and `reset` buttons when multiple team members are added.
- Fixed the last week date range issue while displaying the date between last month's and this month's date.
- Added custom date range filter.
- Implemented grid on the report page.
- Moved `Note` column close to `Project/Client` column.

## Preview

https://www.loom.com/share/06dd136fff024720831165e85b1fd620

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [X] I have manually tested all workflows
- [X] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@gowsik-ragunath As discussed on call please fix the bug on the clear all button & the date range.

**Review by onkar-saeloun — APPROVED** [review]
LGTM @gowsik-ragunath can we plan to merge this PR by today? I am doing some task on same pages and will definitely cause conflicts.

**Comment by gowsik-ragunath** [comment]
Yeah sure @onkar-saeloun, I will request other reviewers to review this PR by today.

**Review by shalapatil — COMMENTED** [review]
Rails code LGTM

**Comment by onkar-saeloun** [comment]
@gowsik-ragunath your changes are causing some type errors in your branch
e.g. `app/javascript/src/components/Reports/timeEntry/index.tsx` line no 142.

**Comment by gowsik-ragunath** [comment]
@onkar-saeloun Could you share the error?

**Comment by onkar-saeloun** [comment]
> @onkar-saeloun Could you share the error?

`Property 'onClickInput' does not exist on type 'IntrinsicAttributes & { setFilterVisibilty: any; resetFilter: any; handleApplyFilter: any; }'.`
there is other one as well should we connect so that I can show it to you.

**Comment by onkar-saeloun** [comment]
After compilation error won't be there. LGTM

**Comment by supriya3105** [comment]
@apoorv1316 Please test this on local and share results.

**Review by apoorv1316 — APPROVED** [review]
LGTM. Few suggestions for which we can open a separate ticket.
1.  When selecting more than one filter the text above the filter icon should show the no of filters applied. Currently,  it's just showing 1.
Screenshot 2022-07-26 at 12 41 17 AM
2. Can we change the toast message from "request failed" to something more relevant when entering invalid custom date input values like '333333'.
@supriya3105 Please let me know if we want to implement these suggestions.

**Comment by supriya3105** [comment]
@apoorv1316 Separate ticket created for suggestions. Merging this PR into staging

**Pull request merged**
