### PR TITLE
Modifications to Time Entry Report page

### PR DESCRIPTION
**Pull request by sanjibroy360**
## Notion card
[https://www.notion.so/saeloun/Modifications-to-Time-Entry-Report-a880bc535076495a8e1a1ab2b5ff7068](https://www.notion.so/saeloun/Modifications-to-Time-Entry-Report-a880bc535076495a8e1a1ab2b5ff7068)

## Summary
- Updated the UI of "Time Entry Report" page as per Figma design.
- Ensured that by default time entry reports will be grouped by client and also will show total logged hours.
- For now hid the share button.
- Show a generic logo in the table header when reports are grouped by team-member / project / client.

## Preview
[https://www.loom.com/share/986384fa99864a5e8b3e2755e9685960](https://www.loom.com/share/986384fa99864a5e8b3e2755e9685960)

Screenshot 2023-02-06 at 6 17 54 PM

Screenshot 2023-02-06 at 6 17 20 PM

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by AkashKale — APPROVED** [review]

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@sanjibroy360 Please watch the loom video for feedback.https://www.loom.com/share/c89b57a8306646878ecb3a649066008f cc @supriya3105

**Review by prasanthchaduvula — APPROVED** [review]

**Comment by sanjibroy360** [comment]
> @sanjibroy360 Please watch the loom video for feedback.https://www.loom.com/share/c89b57a8306646878ecb3a649066008f cc @supriya3105

@apoorv1316 I made all the changes and also handled the scenario when note message, client name, project name is very long. @AkashKale please let me know if you have any suggestion regarding these changes. 
Fix for the issues related to filter button is added to [this PR](https://github.com/saeloun/miru-web/pull/990).

[https://www.loom.com/share/e9a192b3e1ba47019c2ce897e7fd74c0](https://www.loom.com/share/e9a192b3e1ba47019c2ce897e7fd74c0)

**Review by AkashKale — COMMENTED** [review]
Rows with multiple lines description are not looking good. I have added designs for multiple lines.
Please make these changes:
- For single line (same as existing)
image

- Two lines
image

- More than two lines
image

**Review by apoorv1316 — APPROVED** [review]

**Comment by sanjibroy360** [comment]
@AkashKale made UI changes as per Figma design. @apoorv1316  here I've fixed that issue where custom date range inputs were not getting prefilled. Please watch this loom video -

[https://www.loom.com/share/0932618bcb734f3d878a8f15ae88afd8](https://www.loom.com/share/0932618bcb734f3d878a8f15ae88afd8)

**Pull request merged**
