### PR TITLE
Amount format fixed and download invoice error fixed

### PR DESCRIPTION
**Pull request by Shruti-Apte**
## Notion card
https://www.notion.so/saeloun/The-amounts-on-the-invoice-list-page-top-section-should-not-change-as-per-the-filters-applied-3830f3ae13564189b8435a06d161135c
## Summary

- Amount format fixed according to requirement.
- Download invoice error fixed
- made amount static on Invoice dashboard.

## Preview

Before :
Screenshot 2022-11-29 at 11 15 08 AM
 After :
Screenshot 2022-11-29 at 11 14 32 AM

https://www.loom.com/share/b7e41a5507a14aac91e1cb3b0679e959

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code

### CODE REVIEW

**Review by apoorv1316 — APPROVED** [review]

**Review by prasanthchaduvula — APPROVED** [review]

**Comment by supriya3105** [comment]
@Shruti-Apte Please add a video to this PR.

**Comment by vipulnsward** [comment]
Looks good, for such PRs, please add before/after screenshots. Videos work as well but SS are easy and fast to review.

Once we have Integration specs we can make them mandatory on such PRs @supriya3105

**Review by prasanthchaduvula — CHANGES_REQUESTED** [review]
Please remove this `calc_overdue_and_outstanding_and_draft_amount` method from the controller as it is not needed anymore.

**Comment by Shruti-Apte** [comment]
Opened a new PR for same changes because of conflicts [https://github.com/saeloun/miru-web/pull/814]

**Pull request closed without merging**
