### PR TITLE
Auto Saving timesheet data of EntryForm to localstorage

### LINKED ISSUE #1495: auto saving of timesheet entry to local storage until it is saved
### Is your proposal related to a problem?

auto saving of timesheet entry to local storage until it is saved. 

### Describe the solution you'd like

1. Login as any user 
2. On the time tracking tab, click on new entry 
3. Fill the required fields and refresh the screen 
4. After page refresh the previously filled details should be loaded on the page 

### Requirement explanation video
https://www.loom.com/share/bb2907fec1264066ba38299aa46c9a39

### PR DESCRIPTION
**Pull request by Labhk**
fixes #1495

Auto Saving timesheet data to localstorage
- added saveFormDataToLocalStorage  and loadFormDataFromLocalStorage functions 
- on reload get form data from localstorage (using useEffect)

### CODE REVIEW

**Comment by apoorv1316** [comment]
@Labhk Please watch the loom video to understand the exact requirements of this feature.
https://www.loom.com/share/bb2907fec1264066ba38299aa46c9a39

cc @prasanthchaduvula

**Review by akhilgkrishnan — COMMENTED** [review]
@Labhk Can you please add a proper PR title?

**Comment by apoorv1316** [comment]
@Labhk Are you still working on this? Let me know if you need any help.

**Comment by apoorv1316** [comment]
Closing this PR. @supriya3105

**Pull request closed without merging**
