### PR TITLE
Redirect to requested url after login

### PR DESCRIPTION
**Pull request by mayankagnihotri7**
### Notion
[Notion Card](https://www.notion.so/saeloun/After-a-session-has-ended-when-the-user-logs-in-again-the-user-should-be-directed-the-same-page-a-042e3035c4e240eebe59e75db50ab90b)

### Description
- Redirect to the requested URL after login.

### Demo
https://youtu.be/kDZLrApfYSE?feature=shared

### CODE REVIEW

**Review by gowsik-ragunath — APPROVED** [review]
LGTM

**Comment by supriya3105** [comment]
@apoorv1316 Please test

**Comment by supriya3105** [comment]
@mayankagnihotri7 Please add demo video @apoorv1316 please share the test results

**Comment by apoorv1316** [comment]
@ mayankagnihotri7 The user should only be redirected to the same page when the session is timed out. Currently, if a user logs out, he is getting redirected to the same page after logging in. cc @supriya3105

**Comment by prasanthchaduvula** [comment]
@supriya3105 I made the requested changes. Please have a look at the demo.
cc: @apoorv1316

**Review by supriya3105 — APPROVED** [review]

**Comment by supriya3105** [comment]
@prasanthchaduvula Please run the tests locally and merge this PR.

**Pull request merged**
