### PR TITLE
Toaster redesign

### PR DESCRIPTION
**Pull request by gowsik-ragunath**
## Notion card

https://www.notion.so/saeloun/The-toast-message-on-time-tracking-module-is-displayed-for-a-long-time-and-needs-to-change-the-colou-e28b5a4a3223402283125b6b66723a40

## Summary

Redesigned toaster message

## Preview

https://www.loom.com/share/2e128070f8a24f1484d9a33e47d87caf

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [X] I have manually tested all workflows
- [X] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by supriya3105** [comment]
@apoorv1316 please test this

**Review by AkashKale — COMMENTED** [review]
Can we keep the duration for 4 seconds? In the loom video it seems to disappear very fast, even before we are able to read the complete message.

**Review by apoorv1316 — APPROVED** [review]

**Review by akhilgkrishnan — COMMENTED** [review]
@gowsik-ragunath Overall LGTM. But one suggestion can you move all the images to the assets/images folder, And fetch those images in the react component

**Comment by gowsik-ragunath** [comment]
@akhilgkrishnan Moved the SVGs in the public folder to `assets/images` folder.

**Review by akhilgkrishnan — APPROVED** [review]
LGTM

**Comment by supriya3105** [comment]
@AkashKale is this PR approved from your end ?

**Comment by AkashKale** [comment]
> @AkashKale is this PR approved from your end ?

Yes

**Review by supriya3105 — APPROVED** [review]

**Pull request merged**
