### PR TITLE
Add Empty states on time tracking mobile view

### LINKED ISSUE #1152: Fix failing client system spec due to verification of toastr message
### Description
- Toastr messages can't be verified in capybara. It becomes flaky as they run on the browser.

### PR DESCRIPTION
**Pull request by onkar-saeloun**
What-
Added Empty states for time-tracking mobile view.

Fixed #1152 

Why-
If there is no data we were not been able to see any message.

Notion-
https://www.notion.so/saeloun/Implement-empty-states-for-time-tracking-mobile-responsive-page-2c25fc7c0fee4fbca48825745614b20c?pvs=4

Screenshot-
Screenshot 2023-03-20 at 3 48 54 PM

### CODE REVIEW

**Comment by gowsik-ragunath** [comment]
@prasanthchaduvula Fixed #1152 added sleep to wait until the toast element is visible in DOM.

Test is passing in local docker now will post an update on this once the test is passed in Buildkite CI.

**Comment by prasanthchaduvula** [comment]
@gowsik-ragunath Please close the issue if it is resolved on the buildkite

**Comment by gowsik-ragunath** [comment]
Sure, will close

**Comment by onkar-saeloun** [comment]
> @onkar-saeloun The screenshot is incorrect. Please share the screenshot of empty states implementation

@supriya3105 updated the screenshot

**Pull request merged**
