### PR TITLE
Linting and formating code

### LINKED ISSUE #795: Linting and Formatting Code
### Is your proposal related to a problem?
Add configurations for prettier, eslint and rubocop etc...
Update the pre-commit hooks to support all the linting & formatting configs

### PR DESCRIPTION
**Pull request by prasanthchaduvula**
## Issue
Closes #795 

## Summary

- Added husky, prettier, eslint and vscode linting & formatting configuration
## Preview

https://share.vidyard.com/watch/nKvfzrAzgBwpNBBy1WMQh1
## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code

### CODE REVIEW

**Comment by prasanthchaduvula** [comment]
@vipulnsward Please let me know your thoughts

**Comment by vipulnsward** [comment]
Please fix spec, is the rubocop from rails repo? Also did we add rspec rubocop and fixed all failures?

**Comment by prasanthchaduvula** [comment]
@vipulnsward I didn't add the rubocop config yet in this PR. I added husky, prettier, eslint and vscode linting & formatting configurations. If is ok then I will add the rubocop config along with RSpec rubocop support in this PR itself.
Ci checks are failing due to new linitng & formating configs added in this PR which effects all the files as I mentioned in the video. I will format all files according to the new rules then. Please let me know

**Comment by vipulnsward** [comment]
Yes this all needs to go as one PR.

**Comment by apoorv1316** [comment]
@prasanthchaduvula I am re-running the jobs now. Cypress specs won't fail now.

**Pull request merged**
