### PR TITLE
Refactor stripe checkout service

### PR DESCRIPTION
**Pull request by vipulnsward**
What:
- Refactor stripe checkout service

Why:
- To avoid some anti-patterns

### CODE REVIEW

**Comment by vipulnsward** [comment]
@shalapatil please review later in the week when other priority work is done.

**Review by shalapatil — COMMENTED** [review]
👍

**Comment by shalapatil** [comment]
LGTM
@vipulnsward Is this tested locally? If not then @apoorv1316 can you please test this ?

**Comment by shalapatil** [comment]
Tested locally and its working fine!
@apoorv1316 Please test this on staging

**Pull request merged**
