### PR TITLE
Send due invoice payment reminders to client

### PR DESCRIPTION
**Pull request by mayankagnihotri7**
## Notion Card
[Notion Card](https://www.notion.so/saeloun/Send-due-invoice-payment-reminder-to-clients-a2fefb3e47a34f66be3b626a9ce84c7c)

## Description
- Send invoice payment reminders to clients.

### CODE REVIEW

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Few fixes that are required
Screenshot 2023-07-14 at 5 07 26 PM
Screenshot 2023-07-14 at 5 12 18 PM
1.  As per the notion ticket, first the overdue invoices should be listed followed by viewed and then sent invoices.
2. If 1 invoice is selected the text should be "1 invoice selected"
3. If we click on view invoice on the "send payment reminder" modal it opens a new tab but takes us to the client's page instead of the invoice
4.  The email only lists one invoice but I had selected 3 invoices. Also, the CSS needs to be fixed. Check figma design

**Comment by mayankagnihotri7** [comment]
@apoorv1316 I've made the requested changes. Please review.

**Comment by apoorv1316** [comment]
@mayankagnihotri7 Please fix
- Modal should have the invoice sent at the date and due date. @supriya3105 In designs we have an issue date but in notion, it is invoice sent at. Does it mean the same?
- By default, all overdue invoices should be selected. Currently, all invoices are selected.
-

**Comment by mayankagnihotri7** [comment]
@apoorv1316 I've made the requested change for only overdue invoices to be selected by default. Please review.

**Review by prasanthchaduvula — APPROVED** [review]

**Pull request merged**
