### PR TITLE
Broken-edit-project-patch

### PR DESCRIPTION
**Pull request by abinashpa**
## Notion card
https://www.notion.so/saeloun/Admin-Edit-project-has-broken-on-the-client-details-page-41cdccc3da1c4ff5bafb1c90b2346759

## Summary
- Editing project in /clients/:id is causing the app to crash. In this patch, the issue is resolved

## Preview
Screenshot 2022-09-01 at 9 17 21 AM

## Type of change
- API response updated
- More conditions were added to the billable radio button.

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by abinashpa** [comment]
Currently, the billable is not updating will fix it ASAP.

**Comment by apoorv1316** [comment]
@abinashpa The tests are failing also why do I keep seeing old commits on your every PR? Can you please fix it?

**Comment by abinashpa** [comment]
@apoorv1316 All fixes have been incorporated.

**Comment by apoorv1316** [comment]
@abinashpa Wrong notion link in PR description. Please update.

**Review by apoorv1316 — APPROVED** [review]
@abinashpa LGTM

**Review by keshavbiswa — APPROVED** [review]

**Pull request merged**
