### PR TITLE
Fix: Unable to add time entry on week view

### PR DESCRIPTION
**Pull request by mayankagnihotri7**
## Notion card
[Notion card](https://www.notion.so/saeloun/Unable-to-add-time-entry-on-week-view-6ec465d074b44e69936f4cad21a12191)

## Preview

https://user-images.githubusercontent.com/57438322/218504705-77d26019-6fda-4fa1-9177-d22c057b31ac.mp4

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains the same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by supriya3105** [comment]
@mayankagnihotri7 Why isn't this PR assigned to anyone for review. No one will review until it is assigned for review and testing. 
Also, please add summary i.e. what was the problem and how did you fix it & add video of the PR.

**Comment by mayankagnihotri7** [comment]
@supriya3105 I haven't assigned this to anyone for review because currently, I cannot create a video showing it because of the issues with my machine's being unable to run elastic search. I'll assign it to someone for review next week as soon.

**Comment by mayankagnihotri7** [comment]
@supriya3105 Could you please assign this for review to someone?

**Comment by shalapatil** [comment]
@supriya3105 Please ask someone from frontend to review this.

**Comment by supriya3105** [comment]
@mayankagnihotri7 The CI is failing on this PR. Please check and assign to Prasanth for review.

**Comment by mayankagnihotri7** [comment]
@supriya3105 I've already fixed the test cases. This is the issue with buildkite or something.

**Comment by shalapatil** [comment]
LGTM but please get approval from some FE dev

**Review by onkar-saeloun — APPROVED** [review]

**Pull request merged**
