### PR TITLE
Added parallel_spec for faster local testing

### PR DESCRIPTION
**Pull request by prasanthchaduvula**
## Summary

- Added parallel_spec support for faster local testing.
## Preview

**Before**
Screenshot 2022-12-29 at 3 59 52 PM

**After**
Screenshot 2022-12-29 at 4 01 07 PM

### Steps to run
```
# setup
rake parallel:drop
rake parallel:create
rake parallel:prepare
rake parallel:migrate

# run rspec tests
RAILS_ENV=test bundle exec rake parallel:spec
```
 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [x] This change requires a documentation update

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by vipulnsward** [comment]
@prasanthchaduvula please update description with steps to run, as well as update README

**Comment by prasanthchaduvula** [comment]
@vipulnsward I updated the description with the steps

**Comment by vipulnsward** [comment]
We will need to make related changes for Searchkick here- https://github.com/ankane/searchkick#rspec

**Comment by prasanthchaduvula** [comment]
@vipulnsward Please test it again. Implemented https://github.com/ankane/searchkick#factory-bot

**Comment by supriya3105** [comment]
@prasanthchaduvula This PR is assigned to which team member ?

**Comment by prasanthchaduvula** [comment]
As CI is running below 10 mins we are closing this PR

**Pull request closed without merging**
