### PR TITLE
Feature/show fixed working hours on teams page

### PR DESCRIPTION
**Pull request by sudeeptarlekar**
Showed fixed working hours and balance PTO on team details page.

### CODE REVIEW

**Review by harshaanNihal — APPROVED** [review]

**Comment by vipulnsward** [comment]
@sudeeptarlekar is this ready for a merge?

**Comment by sudeeptarlekar** [comment]
Yeah..

**Comment by supriya3105** [comment]
@sudeeptarlekar Can you add the details to description. why are we showing this hours i.e. part of which requirement along with notion ticket.

**Comment by sudeeptarlekar** [comment]
https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=b4528f26f4424af7beaf036262796cb3&p=d095f103fa0d4dc6bdd70eddcac64343&pm=s

**Pull request merged**
