### PR TITLE
Edit Personal details page view

### PR DESCRIPTION
**Pull request by onkar-saeloun**
Note: These changes won't hamper anywhere as currently we are not exposing the routes

## Notion card
https://www.notion.so/saeloun/Integration-of-Personal-details-API-1fbe0517c2094a7b9ef0a3d03ae71659

## Summary

Added UI design for the personal details edit page.

## Preview

https://www.loom.com/share/b4a7f3b3da2e42549602226c1fab8eb8

## Type of change

Please delete options that are not relevant.

- [ ] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Tested on local machine manually

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by onkar-saeloun** [comment]
@apoorv1316, @AkashKale  needed to test on local machine as routes are not open yet and will be available after API integration. Let me know in case of any doubt.

**Comment by apoorv1316** [comment]
@onkar-saeloun What is the route to test it?

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@onkar-saeloun The calendar should close on the outside click. Icons for labels like basic details, contact details, address, and social profiles are missing. Also, which of the fields are mandatory?

**Comment by onkar-saeloun** [comment]
> @onkar-saeloun The calendar should close on the outside click. Icons for labels like basic details, contact details, address, and social profiles are missing. Also, which of the fields are mandatory?

@apoorv1316 Oh I missed the Icons added it now. Regarding calendar outside click and field validations, I will add them in integration PR.

**Review by apoorv1316 — APPROVED** [review]

**Review by prasanthchaduvula — APPROVED** [review]

**Comment by onkar-saeloun** [comment]
This PR should be merged with the following flow-
1. [this](https://github.com/saeloun/miru-web/pull/994) to merge in current PR.
2. current PR to merge in develop

**Comment by onkar-saeloun** [comment]
@vipulnsward can you please have a look in this PR?

**Comment by vipulnsward** [comment]
@onkar-saeloun lets follow up with remaining things in new PR

**Pull request merged**
