### PR TITLE
Added signup, signin, forgot password, reset password API and react components

### PR DESCRIPTION
**Pull request by prasanthchaduvula**
## Notion card
https://www.notion.so/saeloun/Redevelop-Sign-In-page-using-React-1ccc0724feb24e7485a02bdf4c51a17a
https://www.notion.so/saeloun/Redevelop-Sign-Up-page-using-React-58ea46ef7bbd4b239b191ca1863d1063

## Summary

- Created authentication with react components for a signup, signing, forgot password and reset password.
- Created API endpoints for the complete auth flow and integrated them with the frontend.

## Preview
[https://share.vidyard.com/watch/hjA2H2MpCDzcDCSqjsFw3v](https://share.vidyard.com/watch/hjA2H2MpCDzcDCSqjsFw3v)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [ ] I have manually tested all workflows
- [ ] I have performed a self-review of my own code
- [ ] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by apoorv1316** [comment]
@prasanthchaduvula @sanjibroy360 @supriya3105 Please see this loom video. Not all the things are tested yet. I will need some more time for it. https://www.loom.com/share/5df5f2e22eab43ce81b5e05cf9b2db1d

**Comment by supriya3105** [comment]
@sanjibroy360 Please resolve conflicts on this PR. 

@apoorv1316 Can you share the bugs from this PR testing ?

As far I understand it was the google sign in issue . Not able to verify as google sign is not working on staging since migration to DO.

**Comment by supriya3105** [comment]
@prasanthchaduvula Whats happening with this PR ? When can we release it ?

**Comment by prasanthchaduvula** [comment]
@supriya3105 By Today I will finish the devise failing tests and we can release it in our next release. 
@apoorv1316 Have you tested this PR? Please test this PR. So that If anything now working then I can fix it

**Comment by apoorv1316** [comment]
@prasanthchaduvula Please fix the bug in forgot password flow that we discussed on the call. cc @supriya3105

**Review by apoorv1316 — APPROVED** [review]
All test cases which were provided by @prasanthchaduvula are working now. Minor frontend changes need to be made. cc @supriya3105

**Comment by prasanthchaduvula** [comment]
@vipulnsward flaky specs are failing on this PR already present in the current development. Remaining all specs are passing

**Pull request closed without merging**
