### PR TITLE
Mobile responsive team list page

### PR DESCRIPTION
**Pull request by Shruti-Apte**
### **Notion :**
NA
### **What :**
- Mobile responsive team list page
### **Why :**
- Enhancement and requirement.
### **Preview :**
Screenshot 2023-04-18 at 11 38 12 AM

Screenshot 2023-04-18 at 11 38 19 AM

Screenshot 2023-04-18 at 11 37 27 AM

Screenshot 2023-04-24 at 1 56 18 PM

Screenshot 2023-04-24 at 1 56 28 PM

### **Todos** (for testing):
- Tested all team page workflow on mobile responsive screen

### CODE REVIEW

**Comment by apoorv1316** [comment]
@Shruti-Apte Why are we not redirecting to team/:id on clicking on the team member name on mobile view? We have that functionality in the desktop view.

**Comment by Shruti-Apte** [comment]
> @Shruti-Apte Why are we not redirecting to team/:id on clicking on the team member name on mobile view? We have that functionality in the desktop view.

According to the previous code, we navigated the user to team/:id only for the desktop view and restricted access on mobile screens. 
Should I also navigate the user to the team/id page for mobile view?

**Comment by apoorv1316** [comment]
> > @Shruti-Apte Why are we not redirecting to team/:id on clicking on the team member name on mobile view? We have that functionality in the desktop view.
> 
> According to the previous code, we navigated the user to team/:id only for the desktop view and restricted access on mobile screens. Should I also navigate the user to the team/id page for mobile view?
@supriya3105 Can you confirm if we need to navigate users to team/:id in mobile view?

**Comment by supriya3105** [comment]
@Shruti-Apte 

When an admin or owner user taps on a team members name on the teams list page, then the user should be directed to the personal details page of the user. This behaviour should be on both the desktop and mobile responsive pages. 

Hope that clarifies .

**Comment by apoorv1316** [comment]
@Shruti-Apte In web view we don't display edit and delete icons for the owner account. But on mobile, it is there. Can we please fix it?

**Comment by sanjibroy360** [comment]
@Shruti-Apte 
1. The input boxes used in the "Create New User" and "Edit User Details" forms are different from the ones used in the rest of the app. Since you're using Formik, you can use the common "InputField" component found in "app/javascript/src/common/FormikFields/InputField/index.tsx". This will also allow you to show validation errors only when the user clicks on the submit button.
2. The modal should close when the user clicks outside of it or presses the "ESC" key.
3. There's a horizontal scroll issue for Samsung Galaxy S8+ and all iPads. 
4. The `Create New User`, `Edit User Details`, and `Delete User` modal's UI is also breaking for `Samsung Galaxy S8+` 
5. Please fix the alignment of the "+" button in the iPad view.

[https://youtu.be/uIyQUGCFT9E](https://youtu.be/uIyQUGCFT9E)

**Comment by apoorv1316** [comment]
@Shruti-Apte Have you worked on Sanjib's comments?

**Review by sanjibroy360 — APPROVED** [review]

**Pull request merged**
