### PR TITLE
Fixed time entry report bugs and added validation for custom date inputs

### PR DESCRIPTION
**Pull request by sanjibroy360**
## Notion card
[https://www.notion.so/saeloun/Time-entry-report-Bug-96383e9d59df49a7bb625a60054f35ff](https://www.notion.so/saeloun/Time-entry-report-Bug-96383e9d59df49a7bb625a60054f35ff)

## Summary
Fixed time entry report bugs and added validation for custom date inputs.
- The dropdown with menu options should close on clicking anywhere outside the dropdown.
- Remove print option from the dropdown . 
- When selecting more than one filter the text above the filter icon should show the no of filters applied. For time entry report page if number of filters is greater that 1 then only it will show the "Clear all" button.
- Currently the user can enter any value i.e. numbers alphabets and special characters on the custom date range field on the filter panel . Added validation to the custom date range field.
- For invalid custom date range it will disable both submit buttons(calendar's done and filter's apply button).
- Previously after entering any valid from or to date user was not able to enter/type anything. Fixed that issue as well.

Here is the list of valid date formats -
 
```
  "DD MMM YYYY",
  "DD MMMM YYYY",
  "MM/DD/YYYY",
  "YYYY/MM/DD",
  "MM-DD-YYYY",
  "YYYY-MM-DD",
```

## Preview
[https://www.loom.com/share/2922b701e0284205882019ea86f035d6](https://www.loom.com/share/2922b701e0284205882019ea86f035d6)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Refactor (non-breaking and retains same functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [x] I have manually tested all workflows
- [x] I have performed a self-review of my own code
- [x] I have annotated changes in the PR that are relevant to the reviewer
- [ ] I have added automated tests for my code

### CODE REVIEW

**Comment by supriya3105** [comment]
@sanjibroy360 Make sure to assign your PR's to Apoorv for testing

**Review by onkar-saeloun — APPROVED** [review]
LGTM

**Comment by supriya3105** [comment]
@apoorv1316 Why hasn't this been tested today ?

**Comment by apoorv1316** [comment]
> @apoorv1316 Why hasn't this been tested today ?

@supriya3105 My local setup is messed up due to switching between various projects and docker. I am fixing it and will test it when it's fixed.

**Review by apoorv1316 — CHANGES_REQUESTED** [review]
@sanjibroy360 @supriya3105 Please watch this loom video. I am having issues in entering the date for custom dates https://www.loom.com/share/65ca4bdd0a6e42ed99bf1c12fb29f31b

**Comment by sanjibroy360** [comment]
> @sanjibroy360 @supriya3105 Please watch this loom video. I am having issues in entering the date for custom dates https://www.loom.com/share/65ca4bdd0a6e42ed99bf1c12fb29f31b

Apoorv I've fixed all the issues and updated the PR description, preview video. I think there is some issue in the report fetch API because from frontend it's sending correct payload.

**Review by apoorv1316 — APPROVED** [review]
@sanjibroy360 Please take care of this case mentioned in loom https://www.loom.com/share/5fb7eb05a4374d06b332983c34621c4f. Rest LGTM

**Pull request merged**
