### PR TITLE
Fixed manual line item

### PR DESCRIPTION
**Pull request by gowsik-ragunath**
## Notion card

- https://www.notion.so/saeloun/Manual-line-item-added-to-the-invoice-is-not-getting-saved-73c03eab24cb4a2f82bc39b58487b98e

- https://www.notion.so/saeloun/Request-failed-error-toast-on-add-manual-entry-d5cebc12bffc4dd48abeb72a0bf3c51d

## Summary

- Users don't need to press `enter` to add a manual line item in the invoice.
- Implemented the feature that allows users to add multiple line items in both edit and generate invoice pages.
- Added an option to delete manual line items.

### Addition bug fix:

- Fixed the issue in generating PDF using Grover in dev and test environment.
- Rendering invoice view page and invoice mail when company logo is not present.

## Preview

https://www.loom.com/share/ba4b98713ae14759a99d5fa10c611a3e

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
      not work as expected)
- [ ] This change requires a documentation update

### Checklist:

- [X] I have manually tested all workflows
- [X] I have performed a self-review of my own code
- [ ] I have added automated tests for my code

### CODE REVIEW

**Review by supriya3105 — APPROVED** [review]

**Comment by supriya3105** [comment]
@apoorv1316 Please test this flow. This also includes the fix for the bug raised by you https://www.notion.so/saeloun/Request-failed-error-toast-on-add-manual-entry-d5cebc12bffc4dd48abeb72a0bf3c51d.

**Comment by supriya3105** [comment]
@sudeeptarlekar @ajinkyaa Please review this PR.

**Comment by supriya3105** [comment]
@gowsik-ragunath As discussed please check below issues : 
1 . When qyt is in decimal value. 
2. Edit and delete line item
3. Sending invoice.

**Comment by gowsik-ragunath** [comment]
@supriya3105 I have fixed the issue in adding decimal values in the `quantity` field and the issue in generating the invoice using Grover(while sending invoice).

**Pull request merged**
